export default [
	{
		id: 1,
		title: 'AirPods Apple Fones de Ouvido',
		price: 1499,
		img: '/img/produto-01.jpeg',
		qtd: 0,
	},
	{
		id: 2,
		title: 'Capa de silicone para IPhone 8/7 cor Areia - rosa',
		price: 299,
		img: '/img/produto-02.jpeg',
		qtd: 0,
	},
	{
		id: 3,
		title: 'Apple Pencil',
		price: 729,
		img: '/img/produto-03.jpeg',
		qtd: 0,
	},
	{
		id: 4,
		title: 'Magic Mouse 2 - Prateado',
		price: 549,
		img: '/img/produto-04.jpeg',
		qtd: 0,
	},
	{
		id: 5,
		title: 'Caixa prateada de aluminio com pulseira esportiva branca',
		price: 2899,
		img: '/img/produto-05.jpeg',
		qtd: 0,
	},
	{
		id: 6,
		title: 'Cabo de lightning para USB(1m)',
		price: 149,
		img: '/img/produto-06.jpeg',
		qtd: 0,
	},
	{
		id: 7,
		title: 'Smart Keyboard para iPad Pro 12,9 polegadas - inglês(EUA)',
		price: 1099,
		img: '/img/produto-07.jpeg',
		qtd: 0,
	},
	{
		id: 8,
		title: 'Carregador USB da SW apple',
		price: 149,
		img: '/img/produto-08.jpeg',
		qtd: 0,
	},
];
